# Generated by Django 3.2 on 2021-07-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enroll_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='schoolclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentsdetail',
            fields=[
                ('rollnbr', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('s_fname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('date_join', models.DateField()),
                ('c_position', models.BooleanField(default=True)),
                ('sex', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=200)),
                ('fm_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacherdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_fname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('m_number', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=50)),
                ('date_hiring', models.DateField()),
                ('c_position', models.BooleanField(default=True)),
                ('sex', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=200)),
                ('fm_number', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='yearclass',
            fields=[
                ('year', models.IntegerField(default=2021, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teachpaymonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacheramount', models.IntegerField()),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.months')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherdetail')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.yearclass')),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectmarks', models.PositiveSmallIntegerField()),
                ('enrollstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.enroll_student')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentamount', models.IntegerField()),
                ('enrollstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.enroll_student')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.months')),
            ],
        ),
        migrations.AddField(
            model_name='enroll_student',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclasses'),
        ),
        migrations.AddField(
            model_name='enroll_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentsdetail'),
        ),
        migrations.AddField(
            model_name='enroll_student',
            name='years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.yearclass'),
        ),
    ]
