# Generated by Django 3.2 on 2021-07-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subjectmarks',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
